### ISSUE TITLE
false-positives

### ISSUE THREAD

**Issue by hamza-cskn** [alelievr/libft-unit-test#151]
i know sometimes people could not see their mistakes even they checked out carefully. if i am one of them, sorry. however i read the test code and i could not reproduce same issue. when i add a debug printf code to the the test code, it says 'success', but it still assumes failed. 

## split protect issue #119 
i have same issue. i debugged my code. however i couldn't find any problem like you've(@Rodeo314) mentioned. it always allocates exactly amount of necessary bytes. and ensures the string is null-terminated.

my split code: https://paste.ajg0702.us/PMVcFiQ

## atoi 
my atoi code returns same as original atoi. and the test function agrees that but it fails still. i modified the original test code and just added success printf code.

modified test code: https://paste.ajg0702.us/dudCuE4
test result:
<img width="941" alt="atoi test failed" src="https://github.com/alelievr/libft-unit-test/assets/36128276/3b25d01c-edb2-4145-b032-e1ddb1a16f64">
my atoi code: https://paste.ajg0702.us/S5JVaCb

## memmove crash
modified memove test code: https://paste.ajg0702.us/KTO6hgK
test result: 
<img width="722" alt="memmove crash" src="https://github.com/alelievr/libft-unit-test/assets/36128276/75b1a9f3-6588-45e9-b8ca-699ffb6e030c">
my memmove code: https://paste.ajg0702.us/HsVJdAn

you don't have to review/answer for all issues at one time. thank you for interesting.

**Comment by ghost** [comment]
~It would be helpful to show the exact results of the test including the error message, instead of just your code.~

My bad, I was thinking of another issue. Your report does show the errors messages.

**Comment by ghost** [comment]
Your ft_memmove:

```C
copy(-1, len + 1, dst, src);
```

start is -1 and i becomes start, first iteration, dst[i] = src[i] is dst[-1] = src[-1] out of bounds

You want to start at 0, not -1, and you also need to update the condition for the increment selection in copy().

Tester is correctly pointing out an error, the message is misleading because your mistake is probably not typical for this kind of function.

**Comment by ghost** [comment]
ft_atoi: the error message is completely wrong (plus sign and spaces are not the problem), the tester is actually checking ft_atoi(NULL) and expecting a crash, your ft_atoi does not crash.

https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1124.pdf

> 7.1.4 Use of library functions
1 Each of the following statements applies unless explicitly stated otherwise in the detailed descriptions that follow: If an argument to a function has an invalid value (such as a value outside the domain of the function, or a pointer outside the address space of the program, or a null pointer, or a pointer to non-modifiable storage when the corresponding parameter is not const-qualified) or a type (after promotion) not expected by a function with variable number of arguments, the behavior is undefined.

The detailed description of atoi (in section 7.20.1.2) does not state that atoi may accept a null pointer, thus atoi(NULL) is arguably undefined behavior (when str is NULL, crashing or not crashing would be equally correct); the test is a bit pointless. But crashing would be easy, just don't check for NULL input.

**Comment by ghost** [comment]
In your ft_split, word_length:

```C
while (str[i] != c)
	i++;
```

When checking the length of the last word, eventually str[i] will be == 0, you are not checking str[i] and the length will be incorrect for the last word, you need to  `while (str[i] && str[i] != c)`  there too…

```C
result = malloc(sizeof(char *) * (word_amount + 1));
```

…is not protected at all.

```C
res = malloc(sizeof(char) * size);
```

…is not protected properly, because you placed your debug memset before the protection.

Your debug memsets are also buggy, because of the fixed length of 100 you may write past the end of the allocated memory, causing other issues.

**Comment by hamza-cskn** [comment]
Thank you. I fixed my **memmove** and **atoi**. They passes all test now 👍. However i could not fixed my **ft_split**. I added str[i] check to my word length function. I checked out again the number of bytes allocated.

My latest ft_split code: https://pastes.dev/T1yruesF9n

**Comment by hamza-cskn** [comment]
i forgot to add
```c
res = malloc(...)
if (!res)
    return NULL;
```
to my code. after that, everything is done.
