### ISSUE TITLE
ft_putchar

### ISSUE THREAD

**Issue by atenagm** [alelievr/libft-unit-test#37]
it is not possible to print unicode with function putchar

**Comment by alelievr** [comment]
Hello,

It is possible with your ft_putchar to print unicode, anyway this test is displayed as a KO and not a FAIL so your function works even if this test does not pass.

**Comment by amalliar** [comment]
Actually, it's not possible due to a size limitation of 1 byte integer types: the value gets truncated automatically when you pass a big enough int into a function that expects a char. So, unless you know of some magical way to detect overflows on passed parameters, I'd suggest removing this test to avoid further confusion.

On a side note: this test also displays diffs incorrectly:
```
Diffs:
  putchar_fd: |ø|    <-- output of ft_putchar_fd()
ft_putchar_fd: |Ã¸|    <-- expected output
```

**Comment by alelievr** [comment]
@amalliar They changed the subject so it's actually not possible anymore as the new prototype takes a char (was taking an int before).

Therefore, I suppose i'll remove the test.
