### ISSUE TITLE
ft_lstdelone() test should be updated !!

### ISSUE THREAD

**Issue by su-omb** [alelievr/libft-unit-test#71]
The tester is working on the old **ft_lstdelone()** function which has the prototype [ `void ft_lstdelone(t_list **alst, void (*del)(void*, size_t));` ] , while the new subject has a function **ft_lstdelone()** which has the prototype [`void ft_lstdelone(t_list *lst, void (*del)(void*));`] and also the description is changed ! the old function was deleting the content and the node, while the new one deletes just the content ! Please change the test to test just the node's content if it is NULL or not ! 
Thanks in advance !

**Comment by abeaugustijn** [comment]
I submitted a pull request to fix this issue

**Comment by CyberDuck79** [comment]
Your correction is not OK, at least in the french subject it is clear : apply the pointed function on the content (most of the time it would be free()) and free the element (t_list)'.
So the pointed function (wich free the content) is OK no need to change it, it's just that it check if the pointer is NULL after the function but you can't set it to NULL because the first argument is a simple pointer and not a pointer on pointer like in the old subject.
I don't know how to do it but a proper check would be to check if the two memory spaces have been released. (no memory leaks)

**Comment by ggjulio** [comment]
@CyberDuck79 Yes, it's why I haven't figured out a way to fix that test...

**Comment by pafklapper** [comment]
SANDBOX_IRAISE(
free(l);
);
Could be a start?

**Comment by alelievr** [comment]
Hey, i made a quick fix here: https://github.com/alelievr/libft-unit-test/pull/75 but i don't have the new subject and tests (i'm not at school anymore). Can you verify that the tests are compliant with the subject ?

**Comment by ggjulio** [comment]
@alelievr  There is a way in your test to catch a double free and return success ?
ft_lstdelone(l, lstdelone_f);
free(l->content);

if there is no double free, test fail. And if there is, test ok.

**Comment by alelievr** [comment]
Fixed merged but without the double free test, will need to add it in the future c2f60f369fbd5f1125e0479fdfa2d389b5279fc0
